# Generated by Django 2.1.2 on 2018-11-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='session_id',
            new_name='session',
        ),
    ]
