# Generated by Django 2.1.2 on 2019-03-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='key',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
