# Generated by Django 2.1.2 on 2019-03-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_story_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
