# Generated by Django 2.1.2 on 2019-03-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190301_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_points',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
