# Generated by Django 2.1.2 on 2018-12-28 21:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181216_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[core.models.UsernameValidatorAllowSpace()], verbose_name='username'),
        ),
    ]
