# Generated by Django 2.1.2 on 2019-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
