# Generated by Django 2.1.2 on 2019-03-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190301_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_points',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
