# Generated by Django 2.1.2 on 2019-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190329_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='card_type',
            field=models.CharField(choices=[('F', 'FIB'), ('M', 'MODFIB'), ('S', 'SEQ')], default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='velocity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
