# Generated by Django 2.1.2 on 2019-01-21 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181228_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
