# Generated by Django 2.1.2 on 2019-01-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_retroactionitems_sessionmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
