# Generated by Django 2.1.2 on 2019-02-08 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_retrowhatdidnot_retrowhatwentwell'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroBoardItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('action_item_text', models.TextField(choices=[('WWW', 'What Went Well'), ('WDN', 'What Did Not'), ('AI', 'Action Items')], max_length=2000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
