# Generated by Django 2.1.2 on 2019-02-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_retroboarditems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroboarditems',
            old_name='action_item_text',
            new_name='item_text',
        ),
    ]
