# Generated by Django 2.1.2 on 2019-02-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190207_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroboarditems',
            name='item_types',
            field=models.CharField(choices=[('WWW', 'What Went Well'), ('WDN', 'What Did Not'), ('AI', 'Action Items')], default='AI', max_length=3),
        ),
        migrations.AlterField(
            model_name='retroboarditems',
            name='item_text',
            field=models.TextField(max_length=2000),
        ),
    ]
