# Generated by Django 2.1.2 on 2019-02-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190207_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroboarditems',
            old_name='item_types',
            new_name='item_type',
        ),
    ]
