# Generated by Django 2.1.2 on 2019-02-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190207_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retroactionitems',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='retroactionitems',
            name='session',
        ),
        migrations.RemoveField(
            model_name='retrowhatdidnot',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='retrowhatdidnot',
            name='session',
        ),
        migrations.RemoveField(
            model_name='retrowhatwentwell',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='retrowhatwentwell',
            name='session',
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='RetroActionItems',
        ),
        migrations.DeleteModel(
            name='RetroWhatDidNot',
        ),
        migrations.DeleteModel(
            name='RetroWhatWentWell',
        ),
    ]
